using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Abstractions.Models
{
	/// <summary>
	/// Represents a control panel extension.
	/// </summary>
	public class ControlPanelExtensionDefinition : ModelBase
	{
		/// <summary>
		/// Specifies the control panel extension scope.
		/// </summary>
		public enum ControlPanelExtensionScopes
		{
			/// <summary>
			/// The control panel extension is added to the "Settings" control panel.
			/// </summary>
			Global = 0,
			/// <summary>
			/// The control panel extension is added to the "Manage" control panel.
			/// </summary>
			Site = 1
		}

		/// <summary>
		/// Unique record identifier.
		/// </summary>
		/// <remarks>
		/// The Id of a control panel extension definition is generated by a developer and is included in the extension manifest file used to install it.
		/// </remarks>
		public Guid Id { get; set; }

		/// <summary>
		/// Friendly name for the control panel extension definition, used for on-screen display in the administrative interface.
		/// </summary>
		public string FriendlyName { get; set; }

		/// <summary>
		/// Description for the control panel extension definition, used for on-screen display in the administrative interface.
		/// </summary>
		public string Description { get; set; }

		/// <summary>
		/// Controller name for the control panel extension's Controller class.  
		/// </summary>
		public string ControllerName { get; set; }

		/// <summary>
		/// Extension name for the control panel extension's Controller class.  
		/// </summary>
		public string ExtensionName { get; set; }

		/// <summary>
		/// Control panel extension scope.
		/// </summary>
		/// <remarks>
		/// Global-scoped control panel extensions are added to the "settings" control panel, site-scoped control panel extensions are added to the "manage" control panel.
		/// </remarks>
		public ControlPanelExtensionScopes Scope { get; set; }

		/// <summary>
		/// The Action name for the default "Editor" for the control panel extension.
		/// </summary>
		public string EditAction { get; set; }

    /// <summary>
		/// The icon for the control panel extension.
		/// </summary>
		public string Icon { get; set; }

    /// <summary>
		/// Control panel extension help Url.
		/// </summary>
		public string HelpUrl { get; set; }
  }
}
