IF OBJECT_ID(N'Links', N'U') IS NULL
BEGIN
CREATE TABLE [Links] 
(
	[Id] UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
	[ModuleId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NULL,
	[LinkType] NVARCHAR(255) NOT NULL,
	[SortOrder] INT NOT NULL,	
	[CategoryId] UNIQUEIDENTIFIER NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] UNIQUEIDENTIFIER NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [FK_Links_ModuleId] FOREIGN KEY([ModuleId]) REFERENCES PageModules([Id]) ON DELETE CASCADE
);
END;
GO

CREATE UNIQUE CLUSTERED INDEX [PK_Links] ON [Links]([Id]);
GO

IF OBJECT_ID(N'LinkUrls', N'U') IS NULL
BEGIN
CREATE TABLE [LinkUrls] 
(
	[LinkId] UNIQUEIDENTIFIER NOT NULL,
	[Url] NVARCHAR(255) NOT NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] UNIQUEIDENTIFIER NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [FK_LinkUrls_LinkId] FOREIGN KEY([LinkId]) REFERENCES Links([Id]) ON DELETE CASCADE
);
END;
GO

CREATE UNIQUE CLUSTERED INDEX [PK_LinkUrls] ON [LinkUrls]([LinkId]);
GO

IF OBJECT_ID(N'LinkFiles', N'U') IS NULL
BEGIN
CREATE TABLE [LinkFiles] 
(
	[LinkId] UNIQUEIDENTIFIER NOT NULL,
	[FileId] UNIQUEIDENTIFIER NOT NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] UNIQUEIDENTIFIER NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [FK_LinkFiles_LinkId] FOREIGN KEY([LinkId]) REFERENCES Links([Id]) ON DELETE CASCADE
);
END;
GO

CREATE UNIQUE CLUSTERED INDEX [PK_LinkFiles] ON [LinkFiles]([LinkId]);
GO

IF OBJECT_ID(N'LinkPages', N'U') IS NULL
BEGIN
CREATE TABLE [LinkPages] 
(
	[LinkId] UNIQUEIDENTIFIER NOT NULL,
	[PageId] UNIQUEIDENTIFIER NOT NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] UNIQUEIDENTIFIER NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [FK_LinkPages_LinkId] FOREIGN KEY([LinkId]) REFERENCES Links([Id]) ON DELETE CASCADE
);
END;
GO

CREATE UNIQUE CLUSTERED INDEX [PK_LinkPages] ON [LinkPages]([LinkId]);
GO

