CREATE TABLE IF NOT EXISTS [Links] 
(
	[Id] GUID NOT NULL,
	[ModuleId] GUID NOT NULL,
	[Title] TEXT NOT NULL,
	[Description] TEXT NULL,
	[LinkType] INT NOT NULL,
	[SortOrder] INT NOT NULL,	
	[CategoryId] GUID NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] GUID NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] GUID NULL,
	PRIMARY KEY([Id]),
	FOREIGN KEY([ModuleId]) REFERENCES PageModules([Id]) ON DELETE CASCADE,
	FOREIGN KEY([CategoryId]) REFERENCES ListItems([Id]) ON DELETE SET NULL
);
GO

CREATE TABLE IF NOT EXISTS [LinkUrls] 
(
	[LinkId] GUID NOT NULL,
	[Url] TEXT NOT NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] GUID NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] GUID NULL,
	PRIMARY KEY([LinkId]),
	FOREIGN KEY([LinkId]) REFERENCES Links([Id]) ON DELETE CASCADE
);
GO

CREATE TABLE IF NOT EXISTS [LinkFiles] 
(
	[LinkId] GUID NOT NULL,
	[FileId] TEXT NOT NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] GUID NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] GUID NULL,
	PRIMARY KEY([LinkId]),
	FOREIGN KEY([LinkId]) REFERENCES Links([Id]) ON DELETE CASCADE
	FOREIGN KEY([FileId]) REFERENCES FileSystemItems([Id]) ON DELETE CASCADE
);
GO

CREATE TABLE IF NOT EXISTS [LinkPages] 
(
	[LinkId] GUID NOT NULL,
	[PageId] TEXT NOT NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] GUID NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] GUID NULL,
	PRIMARY KEY([LinkId]),
	FOREIGN KEY([LinkId]) REFERENCES Links([Id]) ON DELETE CASCADE
	FOREIGN KEY([PageId]) REFERENCES Pages([Id]) ON DELETE CASCADE
);
GO

