// Moved to Extensions folder

////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//// 
//// This source code was auto-generated by xsd, Version=4.8.4084.0.
//// 
//namespace Nucleus.Abstractions.Models.Manifest {
//    using System.Xml.Serialization;
    
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nucleus/schemas/package/1.0")]
//    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nucleus/schemas/package/1.0", IsNullable=false)]
//    public partial class package {
        
//        /// <remarks/>
//        public string name;
        
//        /// <remarks/>
//        public string version;
        
//        /// <remarks/>
//        public publisher publisher;
        
//        /// <remarks/>
//        public string description;
        
//        /// <remarks/>
//        public compatibility compatibility;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
//        public component[] components;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class publisher {
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string name;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string url;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string email;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class cleanup {
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("containerDefinition", typeof(containerDefinition))]
//        [System.Xml.Serialization.XmlElementAttribute("file", typeof(file))]
//        [System.Xml.Serialization.XmlElementAttribute("folder", typeof(folder))]
//        [System.Xml.Serialization.XmlElementAttribute("layoutDefinition", typeof(layoutDefinition))]
//        [System.Xml.Serialization.XmlElementAttribute("moduleDefinition", typeof(moduleDefinition))]
//        public object[] Items;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class containerDefinition {
        
//        /// <remarks/>
//        public string friendlyName;
        
//        /// <remarks/>
//        public string relativePath;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class file {
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string name;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class folder {
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("file", typeof(file))]
//        [System.Xml.Serialization.XmlElementAttribute("folder", typeof(folder))]
//        public object[] Items;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string name;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class layoutDefinition {
        
//        /// <remarks/>
//        public string friendlyName;
        
//        /// <remarks/>
//        public string relativePath;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class moduleDefinition {
        
//        /// <remarks/>
//        public string friendlyName;
        
//        /// <remarks/>
//        public string classTypeName;
        
//        /// <remarks/>
//        public string viewAction;
        
//        /// <remarks/>
//        public string editAction;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string id;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class component {
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlElementAttribute("cleanup", typeof(cleanup))]
//        [System.Xml.Serialization.XmlElementAttribute("containerDefinition", typeof(containerDefinition))]
//        [System.Xml.Serialization.XmlElementAttribute("file", typeof(file))]
//        [System.Xml.Serialization.XmlElementAttribute("folder", typeof(folder))]
//        [System.Xml.Serialization.XmlElementAttribute("layoutDefinition", typeof(layoutDefinition))]
//        [System.Xml.Serialization.XmlElementAttribute("moduleDefinition", typeof(moduleDefinition))]
//        public object[] Items;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string folderName;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public bool optional;
//    }
    
//    /// <remarks/>
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
//    [System.SerializableAttribute()]
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.ComponentModel.DesignerCategoryAttribute("code")]
//    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nucleus/schemas/package/1.0")]
//    public partial class compatibility {
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string minVersion;
        
//        /// <remarks/>
//        [System.Xml.Serialization.XmlAttributeAttribute()]
//        public string maxVersion;
//    }
//}
