--CREATE TABLE IF NOT EXISTS [$nucleus_extension_name$] 
--(
--	[Id] GUID NOT NULL,
--	[ModuleId] GUID NOT NULL,
--	[Title] TEXT NOT NULL,
--	[Description] TEXT NULL,
--	[CategoryId] GUID NULL,
--	[SortOrder] INT NOT NULL,
--	[FileId] GUID NULL,
--	[DateAdded] DATETIME NULL,
--	[AddedBy] GUID NULL,
--	[DateChanged] DATETIME NULL,
--	[ChangedBy] GUID NULL,
--	PRIMARY KEY([Id]),
--	FOREIGN KEY([ModuleId]) REFERENCES PageModules([Id]) ON DELETE CASCADE
--);
--GO

