{
 "title": "* Nucleus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "up",
    "label": "Up",
    "query": {
     "query": "query_result(up{job=\"$job\", instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Page Requests/second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", route_type=\"page\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(nucleus_application_users_online{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "stat",
   "description": "Nucleus CPU Usage.  ",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_utilization{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 } },
  {
   "title": "Since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "timestamp(changes(up{job=\"$job\", instance=\"$instance\"}[$__interval]) > 0) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Page Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", route_type=\"page\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_server_active_requests{job=\"$job\", instance=\"$instance\"}[$__range])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\",route_type=\"page\"}[$__range]))",
     "legendFormat": "Average Request Duration (pages only)"
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Page Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "nucleus_cache{job=\"$job\", instance=\"$instance\",cache_name=\"pagecache\"}",
     "legendFormat": "Cached Pages"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nucleus_cache{job=\"$job\", instance=\"$instance\",cache_name=\"pagecache\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pages",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(nucleus_routing_page_visited_total{job=\"$job\", instance=\"$instance\"}) by (page_id, page_name)))",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nucleus_cache{job=\"$job\", instance=\"$instance\",cache_name=\"pagecache\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Errors",
   "type": "table",
   "description": "Invalid requests.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "nucleus_routing_error_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}