IF OBJECT_ID(N'Documents', N'U') IS NULL
BEGIN
CREATE TABLE [Documents] 
(
	[Id] UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
	[ModuleId] UNIQUEIDENTIFIER NOT NULL,
	[Title] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NULL,
	[CategoryId] UNIQUEIDENTIFIER NULL,
	[SortOrder] INT NOT NULL,
	[FileId] UNIQUEIDENTIFIER NULL,
	[DateAdded] DATETIME NULL,
	[AddedBy] UNIQUEIDENTIFIER NULL,
	[DateChanged] DATETIME NULL,
	[ChangedBy] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [FK_Documents_ModuleId] FOREIGN KEY([ModuleId]) REFERENCES PageModules([Id]) ON DELETE CASCADE	
);
END;
GO

CREATE UNIQUE CLUSTERED INDEX [PK_Documents] ON [Documents]([Id]);
GO


