using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Abstractions.Models
{
	/// <summary>
	/// Represents an installed container.
	/// </summary>
	/// <remarks>
	/// A container is a wrapper around the output of a module, implemented in Razor.
	/// </remarks>
	public class ContainerDefinition
	{
		/// <summary>
		/// Unique record identifier.
		/// </summary>
		/// <remarks>
		/// The Id of a container is generated by the container's developer and is included in the extension manifest file used to install it.
		/// </remarks>
		public Guid Id { get; set; }

		/// <summary>
		/// Friendly name for the container, used for on-screen display in the administrative interface.
		/// </summary>
		public string FriendlyName { get; set; }

		/// <summary>
		/// Installation path for the container, relative to the Nucleus root folder.
		/// </summary>
		public string RelativePath { get; set; }
	}
}
