using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Abstractions.Models
{
	/// <summary>
	/// Represents an installed Layout.  
	/// </summary>
	/// <remarks>
	/// Layouts are page templates, implemented in Razor.
	/// </remarks>
	public class LayoutDefinition
	{
		/// <summary>
		/// Unique record identifier.
		/// </summary>
		/// <remarks>
		/// The Id of a layout is generated by the container's developer and is included in the extension manifest file used to install it.
		/// </remarks>
		public Guid Id { get; set; }

		/// <summary>
		/// Friendly name for the layout, used for on-screen display in the administrative interface.
		/// </summary>
		public string FriendlyName { get; set; }

		/// <summary>
		/// Installation path for the container, relative to the Nucleus root folder.
		/// </summary>
		public string RelativePath { get; set; }
	}
}
