using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Abstractions.Models
{
	public class ModuleDefinition
	{
		/// <summary>
		/// Unique record identifier.
		/// </summary>
		/// <remarks>
		/// The Id of a module definition is generated by the container's developer and is included in the extension manifest file used to install it.
		/// </remarks>
		public Guid Id { get; set; }

		/// <summary>
		/// Friendly name for the module definition, used for on-screen display in the administrative interface.
		/// </summary>
		public string FriendlyName { get; set; }

		/// <summary>
		/// Assembly-qualified class name for the module's Controller class.  The Controller class must inherit Microsoft.AspNetCore.Mvc.Controller
		/// </summary>
		public string ClassTypeName { get; set; }

		/// <summary>
		/// The Action name for the default "View" of the module.
		/// </summary>
		public string ViewAction { get; set; }

		/// <summary>
		/// The Action name for the default "Editor" for the module.
		/// </summary>
		public string EditAction { get; set; }
	}
}
