using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Abstractions.Models.Mail
{
	/// <summary>
	/// Represents the email templates in use by a site.
	/// </summary>
	/// <remarks>
	/// This class is generated by using the MailSettingsExtensions.GetSiteTemplateSelections extension, which reads values from a site's
	/// name/value settings into this class.
	/// </remarks>
	public class SiteTemplateSelections
	{
		/// <summary>
		/// If set, specifies the Id of the email sent to new users when they sign up.
		/// </summary>
		public Guid? WelcomeNewUserTemplateId { get; set; }
		/// <summary>
		/// If set, specfies the Id of the email sent to users when they request a password reset.
		/// </summary>
		public Guid? PasswordResetTemplateId { get; set; }
		/// <summary>
		/// If set, specifies the Id of the email sent to users when they request a user name reminder.
		/// </summary>
		public Guid? AccountNameReminderTemplateId { get; set; }
		

	}
}
