using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Abstractions.Models.Mail
{
	/// <summary>
	/// Represents the email templates in use by a site.
	/// </summary>
	/// <remarks>
	/// This class is generated by using the MailSettingsExtensions.GetSiteTemplateSelections extension, which reads values from a site's
	/// name/value settings into this class.
	/// </remarks>
	public class SiteTemplateSelections
	{
		public Guid? WelcomeNewUserTemplateId { get; set; }
		public Guid? PasswordResetTemplateId { get; set; }
		public Guid? AccountNameReminderTemplateId { get; set; }
		

	}
}
